// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protos/coupon/v1/coupon.proto

package couponv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *Coupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Coupon) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *Coupon) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponLimit   uint32                 `protobuf:"varint,2,opt,name=coupon_limit,json=couponLimit,proto3" json:"coupon_limit,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Coupons       []*Coupon              `protobuf:"bytes,8,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *Campaign) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Campaign) GetCouponLimit() uint32 {
	if x != nil {
		return x.CouponLimit
	}
	return 0
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Campaign) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Campaign) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Campaign) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponLimit   uint32                 `protobuf:"varint,1,opt,name=coupon_limit,json=couponLimit,proto3" json:"coupon_limit,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCampaignRequest) GetCouponLimit() uint32 {
	if x != nil {
		return x.CouponLimit
	}
	return 0
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateCampaignRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type CreateCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint32                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignRequest) GetCampaignId() uint32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *GetCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type IssueCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    uint32                 `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponRequest) Reset() {
	*x = IssueCouponRequest{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponRequest) ProtoMessage() {}

func (x *IssueCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponRequest.ProtoReflect.Descriptor instead.
func (*IssueCouponRequest) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *IssueCouponRequest) GetCampaignId() uint32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type IssueCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupon        *Coupon                `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse) Reset() {
	*x = IssueCouponResponse{}
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse) ProtoMessage() {}

func (x *IssueCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_coupon_v1_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse) Descriptor() ([]byte, []int) {
	return file_protos_coupon_v1_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *IssueCouponResponse) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

var File_protos_coupon_v1_coupon_proto protoreflect.FileDescriptor

const file_protos_coupon_v1_coupon_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/coupon/v1/coupon.proto\x12\x10protos.coupon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x06Coupon\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x127\n" +
	"\texpire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"\xcc\x02\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fcoupon_limit\x18\x02 \x01(\rR\vcouponLimit\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x125\n" +
	"\bstart_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x122\n" +
	"\acoupons\x18\b \x03(\v2\x18.protos.coupon.v1.CouponR\acoupons\"\xda\x01\n" +
	"\x15CreateCampaignRequest\x12!\n" +
	"\fcoupon_limit\x18\x01 \x01(\rR\vcouponLimit\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bstart_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"P\n" +
	"\x16CreateCampaignResponse\x126\n" +
	"\bcampaign\x18\x01 \x01(\v2\x1a.protos.coupon.v1.CampaignR\bcampaign\"5\n" +
	"\x12GetCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\rR\n" +
	"campaignId\"M\n" +
	"\x13GetCampaignResponse\x126\n" +
	"\bcampaign\x18\x01 \x01(\v2\x1a.protos.coupon.v1.CampaignR\bcampaign\"5\n" +
	"\x12IssueCouponRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\rR\n" +
	"campaignId\"G\n" +
	"\x13IssueCouponResponse\x120\n" +
	"\x06coupon\x18\x01 \x01(\v2\x18.protos.coupon.v1.CouponR\x06coupon2\xba\x02\n" +
	"\x15CouponIssuanceService\x12e\n" +
	"\x0eCreateCampaign\x12'.protos.coupon.v1.CreateCampaignRequest\x1a(.protos.coupon.v1.CreateCampaignResponse\"\x00\x12\\\n" +
	"\vGetCampaign\x12$.protos.coupon.v1.GetCampaignRequest\x1a%.protos.coupon.v1.GetCampaignResponse\"\x00\x12\\\n" +
	"\vIssueCoupon\x12$.protos.coupon.v1.IssueCouponRequest\x1a%.protos.coupon.v1.IssueCouponResponse\"\x00BIZGgithub.com/jackgihokim/coupon-issuance-system/protos/coupon/v1;couponv1b\x06proto3"

var (
	file_protos_coupon_v1_coupon_proto_rawDescOnce sync.Once
	file_protos_coupon_v1_coupon_proto_rawDescData []byte
)

func file_protos_coupon_v1_coupon_proto_rawDescGZIP() []byte {
	file_protos_coupon_v1_coupon_proto_rawDescOnce.Do(func() {
		file_protos_coupon_v1_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_coupon_v1_coupon_proto_rawDesc), len(file_protos_coupon_v1_coupon_proto_rawDesc)))
	})
	return file_protos_coupon_v1_coupon_proto_rawDescData
}

var file_protos_coupon_v1_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_coupon_v1_coupon_proto_goTypes = []any{
	(*Coupon)(nil),                 // 0: protos.coupon.v1.Coupon
	(*Campaign)(nil),               // 1: protos.coupon.v1.Campaign
	(*CreateCampaignRequest)(nil),  // 2: protos.coupon.v1.CreateCampaignRequest
	(*CreateCampaignResponse)(nil), // 3: protos.coupon.v1.CreateCampaignResponse
	(*GetCampaignRequest)(nil),     // 4: protos.coupon.v1.GetCampaignRequest
	(*GetCampaignResponse)(nil),    // 5: protos.coupon.v1.GetCampaignResponse
	(*IssueCouponRequest)(nil),     // 6: protos.coupon.v1.IssueCouponRequest
	(*IssueCouponResponse)(nil),    // 7: protos.coupon.v1.IssueCouponResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_protos_coupon_v1_coupon_proto_depIdxs = []int32{
	8,  // 0: protos.coupon.v1.Coupon.expire_at:type_name -> google.protobuf.Timestamp
	8,  // 1: protos.coupon.v1.Coupon.issued_at:type_name -> google.protobuf.Timestamp
	8,  // 2: protos.coupon.v1.Campaign.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: protos.coupon.v1.Campaign.start_at:type_name -> google.protobuf.Timestamp
	8,  // 4: protos.coupon.v1.Campaign.end_at:type_name -> google.protobuf.Timestamp
	0,  // 5: protos.coupon.v1.Campaign.coupons:type_name -> protos.coupon.v1.Coupon
	8,  // 6: protos.coupon.v1.CreateCampaignRequest.start_at:type_name -> google.protobuf.Timestamp
	8,  // 7: protos.coupon.v1.CreateCampaignRequest.end_at:type_name -> google.protobuf.Timestamp
	1,  // 8: protos.coupon.v1.CreateCampaignResponse.campaign:type_name -> protos.coupon.v1.Campaign
	1,  // 9: protos.coupon.v1.GetCampaignResponse.campaign:type_name -> protos.coupon.v1.Campaign
	0,  // 10: protos.coupon.v1.IssueCouponResponse.coupon:type_name -> protos.coupon.v1.Coupon
	2,  // 11: protos.coupon.v1.CouponIssuanceService.CreateCampaign:input_type -> protos.coupon.v1.CreateCampaignRequest
	4,  // 12: protos.coupon.v1.CouponIssuanceService.GetCampaign:input_type -> protos.coupon.v1.GetCampaignRequest
	6,  // 13: protos.coupon.v1.CouponIssuanceService.IssueCoupon:input_type -> protos.coupon.v1.IssueCouponRequest
	3,  // 14: protos.coupon.v1.CouponIssuanceService.CreateCampaign:output_type -> protos.coupon.v1.CreateCampaignResponse
	5,  // 15: protos.coupon.v1.CouponIssuanceService.GetCampaign:output_type -> protos.coupon.v1.GetCampaignResponse
	7,  // 16: protos.coupon.v1.CouponIssuanceService.IssueCoupon:output_type -> protos.coupon.v1.IssueCouponResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protos_coupon_v1_coupon_proto_init() }
func file_protos_coupon_v1_coupon_proto_init() {
	if File_protos_coupon_v1_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_coupon_v1_coupon_proto_rawDesc), len(file_protos_coupon_v1_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_coupon_v1_coupon_proto_goTypes,
		DependencyIndexes: file_protos_coupon_v1_coupon_proto_depIdxs,
		MessageInfos:      file_protos_coupon_v1_coupon_proto_msgTypes,
	}.Build()
	File_protos_coupon_v1_coupon_proto = out.File
	file_protos_coupon_v1_coupon_proto_goTypes = nil
	file_protos_coupon_v1_coupon_proto_depIdxs = nil
}
